/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Classes.DoublyLinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Gianne Bacay
 */
public class CipherSchemes_Bacay extends javax.swing.JFrame {
    
    /**
     * Creates new form CipherSchemes
     */
    public CipherSchemes_Bacay() {
        initComponents();
        
    }
    private static DoublyLinkedList list = new DoublyLinkedList();
    
    // Caesar Cipher Encryption using DoublyLinkedList
    public static String caesarEncrypt(String message, int key) {
        list.MakeEmpty();
        
        for (int i = 0; i < message.length(); i++) {
            char ch = message.charAt(i);

            if (Character.isLetter(ch)) {
                char base = Character.isLowerCase(ch) ? 'a' : 'A';
                int shift = (ch - base + key) % 26;
                char encryptedChar = (char) (base + shift);
                DoublyLinkedList.Add(encryptedChar); // Use DoublyLinkedList for character manipulation
            } else {
                DoublyLinkedList.Add(ch); // Use DoublyLinkedList for non-letter characters
            }
        }
        return list.toString();
    }

    // Caesar Cipher Decryption using DoublyLinkedList
    public static String caesarDecrypt(String message, int key) {
        list.MakeEmpty();
        
        for (int i = 0; i < message.length(); i++) {
            char ch = message.charAt(i);

            if (Character.isLetter(ch)) {
                char base = Character.isLowerCase(ch) ? 'a' : 'A';
                int shift = (ch - base - key + 26) % 26;
                char decryptedChar = (char) (base + shift);
                list.Add(decryptedChar); // Use DoublyLinkedList for character manipulation
            } else {
                list.Add(ch); // Use DoublyLinkedList for non-letter characters
            }
        }
        return list.toString();
    }

    // Vigenere Cipher Encryption using DoublyLinkedList
    public static String vigenereEncrypt(String message, String key) {
        list.MakeEmpty();
        int keyLength = key.length();
        int keyIndex = 0;

        for (int i = 0; i < message.length(); i++) {
            char ch = message.charAt(i);

            if (Character.isLetter(ch)) {
                char base = Character.isLowerCase(ch) ? 'a' : 'A';
                char keyChar = key.charAt(keyIndex % keyLength);
                int shift = keyChar - base;
                char encryptedChar = (char) ((ch - base + shift) % 25 + base);
                list.Add(encryptedChar); // Use DoublyLinkedList for character manipulation
                keyIndex++;
            } else {
                list.Add(ch); // Use DoublyLinkedList for non-letter characters
            }
        }
        return list.toString();
    }

    // Vigenere Cipher Decryption using DoublyLinkedList
    public static String vigenereDecrypt(String message, String key) {
        list.MakeEmpty();
        int keyLength = key.length();
        int keyIndex = 0;

        for (int i = 0; i < message.length(); i++) {
            char ch = message.charAt(i);

            if (Character.isLetter(ch)) {
                char base = Character.isLowerCase(ch) ? 'a' : 'A';
                char keyChar = key.charAt(keyIndex % keyLength);
                int shift = keyChar - base;
                char decryptedChar = (char) ((ch - base - shift + 25) % 25 + base);
                list.Add(decryptedChar); // Use DoublyLinkedList for character manipulation
                keyIndex++;
            } else {
                list.Add(ch); // Use DoublyLinkedList for non-letter characters
            }
        }
        return list.toString();
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        ceasarLayer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        keyBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        messageBox = new javax.swing.JTextArea();
        resultBox = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        BGlayer = new javax.swing.JLabel();
        vigenereLayer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        keyBox1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        resultBox1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        messageBox1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        BGlayer1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 510));
        setMinimumSize(new java.awt.Dimension(800, 510));

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(800, 510));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(800, 510));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 510));

        ceasarLayer.setMaximumSize(new java.awt.Dimension(800, 510));
        ceasarLayer.setMinimumSize(new java.awt.Dimension(800, 510));
        ceasarLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Enter Message:");
        ceasarLayer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 220, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Enter Key [0-25]:");
        ceasarLayer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 130, -1));

        keyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyBoxActionPerformed(evt);
            }
        });
        ceasarLayer.add(keyBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 130, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Result:");
        ceasarLayer.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Encrypt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        ceasarLayer.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 90, -1));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Decrypt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ceasarLayer.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 90, -1));

        messageBox.setColumns(20);
        messageBox.setRows(5);
        jScrollPane3.setViewportView(messageBox);

        ceasarLayer.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 400, 110));

        resultBox.setColumns(20);
        resultBox.setRows(5);
        ceasarLayer.add(resultBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 230, 60));

        jButton6.setText("clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        ceasarLayer.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 90, -1));

        BGlayer.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gianne Bacay\\Documents\\NetBeansProjects\\CipherSchemes\\src\\main\\java\\Resources\\CEASAR.png")); // NOI18N
        ceasarLayer.add(BGlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        jTabbedPane1.addTab("Ceasar Cipher", ceasarLayer);

        vigenereLayer.setMaximumSize(new java.awt.Dimension(800, 510));
        vigenereLayer.setMinimumSize(new java.awt.Dimension(800, 510));
        vigenereLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Enter Message:");
        vigenereLayer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Enter Keyword:");
        vigenereLayer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 120, -1));

        keyBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyBox1ActionPerformed(evt);
            }
        });
        vigenereLayer.add(keyBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Result:");
        vigenereLayer.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 100, 20));

        jButton3.setBackground(new java.awt.Color(102, 255, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Encrypt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        vigenereLayer.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 90, -1));

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Decrypt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        vigenereLayer.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 90, -1));

        resultBox1.setColumns(20);
        resultBox1.setRows(5);
        vigenereLayer.add(resultBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 230, 60));

        messageBox1.setColumns(20);
        messageBox1.setRows(5);
        jScrollPane4.setViewportView(messageBox1);

        vigenereLayer.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 400, 110));

        jButton5.setText("clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        vigenereLayer.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 90, -1));

        BGlayer1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gianne Bacay\\Downloads\\CEASAR (1).png")); // NOI18N
        vigenereLayer.add(BGlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 800, 510));

        jTabbedPane1.addTab("Vigenere Cipher", vigenereLayer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(messageBox.getText().isEmpty() || keyBox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all fields");
        }
        else{
            String message = messageBox.getText().trim();
            String key = keyBox.getText().trim();
            int caesarKey = Integer.parseInt(key);
            String encryptedMessage = caesarEncrypt(message, caesarKey);
            resultBox.setText("");
            resultBox.setText(encryptedMessage);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void keyBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(messageBox1.getText().isEmpty() || keyBox1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all fields");
        }
        else{
            String message = messageBox1.getText().trim();
            String vigenereKey = keyBox1.getText().trim();
            String encryptedMessage = vigenereEncrypt(message, vigenereKey);
            resultBox1.setText("");
            resultBox1.setText(encryptedMessage);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(messageBox.getText().isEmpty() || keyBox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all fields");
        }
        else{
            String message = messageBox.getText().trim();
            String key = keyBox.getText().trim();
            int caesarKey = Integer.parseInt(key);
            String decryptedMessage = caesarDecrypt(message, caesarKey);
            resultBox.setText("");
            resultBox.setText(decryptedMessage);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(messageBox1.getText().isEmpty() || keyBox1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all fields");
        }
        else{
            String message = messageBox1.getText().trim();
            String vigenereKey = keyBox1.getText().trim();
            String decryptedMessage = vigenereDecrypt(message, vigenereKey);
            resultBox1.setText("");
            resultBox1.setText(decryptedMessage);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        resultBox1.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        resultBox.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CipherSchemes_Bacay frame = new CipherSchemes_Bacay();
                frame.setResizable(false);
                frame.setTitle("Cipher Schemes Converter");
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGlayer;
    private javax.swing.JLabel BGlayer1;
    private javax.swing.JPanel ceasarLayer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField keyBox;
    private javax.swing.JTextField keyBox1;
    private javax.swing.JTextArea messageBox;
    private javax.swing.JTextArea messageBox1;
    private javax.swing.JTextArea resultBox;
    private javax.swing.JTextArea resultBox1;
    private javax.swing.JPanel vigenereLayer;
    // End of variables declaration//GEN-END:variables
}
